### ISSUE TITLE
3d sculpting

### ISSUE THREAD

**Issue by elkhalafy** [RonenNess/MonoGame-SceneGraph#1]
Hello, 

Can you wrap or Port SculptGL As Library or SDK for .NET Platform ( C# ) and rendering using OpenTK ?

**Comment by RonenNess** [comment]
Hello @elkhalafy,
Are you sure you are on the right git repo? Sounds like you meant to open this ticket on SculptGL repository (or maybe I misunderstood you).

**Comment by elkhalafy** [comment]
Yes I'm Sure, You can use Javascript and C# and 3d Graphics and you can Port It for .NET Platform ?
you can do it ?

what do you think ?

**Comment by RonenNess** [comment]
This is not what github "Issues" are for ([https://guides.github.com/features/issues/](https://guides.github.com/features/issues/)). Issues are meant to be for problems / features / etc. related to the **specific repo they are opened on**. Not for personal, unrelated requests.

I'm not available for projects at the moment. You should probably ask someone who's related to the SculptGL project.

Thanks.
